version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
      - "rust"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "actions"
    schedule:
      interval: "daily"
