[package]
name = "litevfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ltx = { git = "ssh://git@github.com/superfly/ltx-rs.git", branch = "main" }
rand = "0.8"
sqlite-vfs = "0.2"
