name: "Push"
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  VERSION: "${{ github.event_name == 'release' && github.event.release.name || github.sha }}"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all --check
      - name: cargo clippy
        run: cargo clippy --all-features -- --deny warnings
      - name: cargo check
        run: cargo check

  test:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2

      - name: Run unit tests
        run: cargo test --lib

  build:
    name: "Build"
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
            soname: "liblitevfs.so"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-musl"
            soname: "liblitevfs.so"
          - os: "ubuntu-latest"
            target: "aarch64-unknown-linux-gnu"
            soname: "liblitevfs.so"
          - os: "ubuntu-latest"
            target: "aarch64-unknown-linux-musl"
            soname: "liblitevfs.so"
          - os: "macos-latest"
            target: "x86_64-apple-darwin"
            soname: "liblitevfs.dylib"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
            soname: "liblitevfs.dylib"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            soname: "litevfs.dll"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --package litevfs --release
          cd target/${{ matrix.target }}/release
          tar -czvf litevfs-${{ env.VERSION }}-${{ matrix.target }}.tar.gz ${{ matrix.soname }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: litevfs-${{ env.VERSION }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.soname }}
          if-no-files-found: error

  build-wasm:
    name: "Build WASM"
    runs-on: "ubuntu-latest"
    env:
      EM_VERSION: 3.1.42
      EM_CACHE_FOLDER: 'emsdk-cache'

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Install wasm32-unknown-emscripten target
        run: rustup target add wasm32-unknown-emscripten
      - name: Install WABT
        run: sudo apt-get install -y wabt
      - uses: Swatinem/rust-cache@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.EM_CACHE_FOLDER }}
          key: ${{ env.EM_VERSION }}-${{ runner.os }}

      - name: Build
        run: |
          cargo xtask build-wasm
          cd target
          tar -czvf sqlite3-wasm-${{ env.VERSION }}.tar.gz sqlite3-wasm

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite3-wasm-${{ env.VERSION }}
          path: target/sqlite3-wasm
          if-no-files-found: error
